server:
  port: 8080
  servlet:
    context-path: /oa
#数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.41.115.14:3306/oa?useSSL=false&characterEncoding=UTF-8
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
 #redis配置
  redis:
    database: 0
    port: 6379
    host: localhost
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 5000ms
#静态资源配置
  mvc:
    static-path-pattern: /**

#mybatis配置
mybatis:
  type-aliases-package: com.yang.oa.entity
  mapper-locations: classpath:daoImpl/*.xml
#logback配置
logging:
  config: classpath:logback-spring.xml

